### PR TITLE
add missing include for stream (required for std::ofstream)

### PR DESCRIPTION
**Pull request by boegel**
fix for compilation error with GCC 12.3.0:

```
error: variable std::ofstream summary_out has initializer but incomplete type
```

Note: to make the build of dorado 0.6.1 fully work with GCC 12.3.0, I also had to use `-Wno-error`, see also #779

### CODE REVIEW

**Comment by iiSeymour** [comment]
Thanks @boegel this was fixed in v0.7 by https://github.com/nanoporetech/dorado/commit/f197cbad5bfc646cd4ad8a69b897187448c1378d.
